### ISSUE TITLE
fixed version because he doesnt fix it

### ISSUE THREAD

**Issue by AsafCN** [paulosafky/s_csgo_knives#1]
**Never mind it does not working and i dont know why**

I cant upload the whole file so i am puting a link for you to download
[file-upload](https://www.file-upload.net/download-15345266/knifes.zip.html)
you can open the readme.md in the file and scroll down for qbcore items.lua and weapon.lua code

**Comment by paulosafky** [comment]
You didnt fix nothing but thanks
